/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OportunidadeIdRouteImport } from './routes/oportunidade.$id'
import { Route as OnboardingObstaculosRouteImport } from './routes/onboarding.obstaculos'
import { Route as OnboardingDisponibilidadeRouteImport } from './routes/onboarding.disponibilidade'
import { Route as OnboardingDestinoRouteImport } from './routes/onboarding.destino'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppJornadaRouteImport } from './routes/_app.jornada'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppExplorarRouteImport } from './routes/_app.explorar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadeIdRoute = OportunidadeIdRouteImport.update({
  id: '/oportunidade/$id',
  path: '/oportunidade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingObstaculosRoute = OnboardingObstaculosRouteImport.update({
  id: '/onboarding/obstaculos',
  path: '/onboarding/obstaculos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDisponibilidadeRoute =
  OnboardingDisponibilidadeRouteImport.update({
    id: '/onboarding/disponibilidade',
    path: '/onboarding/disponibilidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingDestinoRoute = OnboardingDestinoRouteImport.update({
  id: '/onboarding/destino',
  path: '/onboarding/destino',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppJornadaRoute = AppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorarRoute = AppExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/explorar': typeof AppExplorarRoute
  '/home': typeof AppHomeRoute
  '/jornada': typeof AppJornadaRoute
  '/perfil': typeof AppPerfilRoute
  '/onboarding/destino': typeof OnboardingDestinoRoute
  '/onboarding/disponibilidade': typeof OnboardingDisponibilidadeRoute
  '/onboarding/obstaculos': typeof OnboardingObstaculosRoute
  '/oportunidade/$id': typeof OportunidadeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/explorar': typeof AppExplorarRoute
  '/home': typeof AppHomeRoute
  '/jornada': typeof AppJornadaRoute
  '/perfil': typeof AppPerfilRoute
  '/onboarding/destino': typeof OnboardingDestinoRoute
  '/onboarding/disponibilidade': typeof OnboardingDisponibilidadeRoute
  '/onboarding/obstaculos': typeof OnboardingObstaculosRoute
  '/oportunidade/$id': typeof OportunidadeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/_app/explorar': typeof AppExplorarRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/jornada': typeof AppJornadaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/onboarding/destino': typeof OnboardingDestinoRoute
  '/onboarding/disponibilidade': typeof OnboardingDisponibilidadeRoute
  '/onboarding/obstaculos': typeof OnboardingObstaculosRoute
  '/oportunidade/$id': typeof OportunidadeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/explorar'
    | '/home'
    | '/jornada'
    | '/perfil'
    | '/onboarding/destino'
    | '/onboarding/disponibilidade'
    | '/onboarding/obstaculos'
    | '/oportunidade/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/explorar'
    | '/home'
    | '/jornada'
    | '/perfil'
    | '/onboarding/destino'
    | '/onboarding/disponibilidade'
    | '/onboarding/obstaculos'
    | '/oportunidade/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/_app/explorar'
    | '/_app/home'
    | '/_app/jornada'
    | '/_app/perfil'
    | '/onboarding/destino'
    | '/onboarding/disponibilidade'
    | '/onboarding/obstaculos'
    | '/oportunidade/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OnboardingDestinoRoute: typeof OnboardingDestinoRoute
  OnboardingDisponibilidadeRoute: typeof OnboardingDisponibilidadeRoute
  OnboardingObstaculosRoute: typeof OnboardingObstaculosRoute
  OportunidadeIdRoute: typeof OportunidadeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidade/$id': {
      id: '/oportunidade/$id'
      path: '/oportunidade/$id'
      fullPath: '/oportunidade/$id'
      preLoaderRoute: typeof OportunidadeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/obstaculos': {
      id: '/onboarding/obstaculos'
      path: '/onboarding/obstaculos'
      fullPath: '/onboarding/obstaculos'
      preLoaderRoute: typeof OnboardingObstaculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/disponibilidade': {
      id: '/onboarding/disponibilidade'
      path: '/onboarding/disponibilidade'
      fullPath: '/onboarding/disponibilidade'
      preLoaderRoute: typeof OnboardingDisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/destino': {
      id: '/onboarding/destino'
      path: '/onboarding/destino'
      fullPath: '/onboarding/destino'
      preLoaderRoute: typeof OnboardingDestinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jornada': {
      id: '/_app/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AppJornadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorar': {
      id: '/_app/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AppExplorarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExplorarRoute: typeof AppExplorarRoute
  AppHomeRoute: typeof AppHomeRoute
  AppJornadaRoute: typeof AppJornadaRoute
  AppPerfilRoute: typeof AppPerfilRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExplorarRoute: AppExplorarRoute,
  AppHomeRoute: AppHomeRoute,
  AppJornadaRoute: AppJornadaRoute,
  AppPerfilRoute: AppPerfilRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OnboardingDestinoRoute: OnboardingDestinoRoute,
  OnboardingDisponibilidadeRoute: OnboardingDisponibilidadeRoute,
  OnboardingObstaculosRoute: OnboardingObstaculosRoute,
  OportunidadeIdRoute: OportunidadeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
